name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline" ]
    types:
    - completed  
  
jobs: 
  build:
    run-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull julioflores781/pruebagitha:latest
    - name: Delete Old docker container
      run: sudo docker rm -f e-comerce-container || true
    - name: Run Docker Container
      run: docker run -d -p 8080:5173 -p 3001:3000 -name e-comerce-container julioflores781/pruebagitha
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t julioflores781/pruebagitha .
    - name: Push to Dockerhub
      run: docker push julioflores781/pruebagitha:latest

# permissions:
#   contents: read

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     environment:
#       name: ${{github.ref_name}}
#       url: ${{steps.deploy.outputs.vm_url}}
    
#     steps:
#     - id: deploy
#       name: Deploy
#       uses: bitovi/github-actions-deploy-docker-to-ec2@v0.4.2
#       with:
#         role-session-name: awssyncsession
#         role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
#         aws-region: ${{ secrets.AWS_REGION }}

    # steps:
    #   -
    #     name: Set up QEMU
    #     uses: docker/setup-qemu-action@v3
    #   -
    #     name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v3
    #   -
    #     name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
    #   -
    #     name: Build and push
    #     uses: docker/build-push-action@v5
    #     with:
    #       push: true
    #       tags: julioflores781/pruebagitha:${{ github.sha }}

  # deploy-to-cluster:
  #   name: deploy to cluster
  #   runs-on: ubuntu-latest
  #   needs: docker
  #   steps:
  #   -
  #     name: deploy to cluster
  #     uses: steebchen/kubectl@v2.0.0
  #     with:
  #       config: ${{ secrets.KUBE_CONFIG_DATA }}
  #       command: -n prueba set image --record deployment/prueba-gha prueba-gha=julioflores781/pruebagitha:${{ github.sha }}
  #   -
  #     name: verify deployment
  #     uses: steebchen/kubectl@v2.0.0
  #     env:
  #       KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  #       KUBECTL_VERSION: "1.28"
  #     with:
  #       config: ${{ secrets.KUBE_CONFIG_DATA }}
  #       command: -n prueba rollout status deployment/prueba-gha
