name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline" ]
    types:
    - completed  
  
jobs: 
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull julioflores781/pruebagitha:latest
    - name: Delete Old docker container
      run: sudo docker rm -f e-comerce-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:5173 -p 3001:3000 -name e-comerce-container julioflores781/pruebagitha
